version: "3.9"

services:
  vm1:
    image: ${DOCKER_QEMU_IMAGE:-ghcr.io/munenick/docker-qemu:latest}
    container_name: ${VM1_NAME:-vm1}
    devices:
      - /dev/kvm:/dev/kvm
    volumes:
      - ./images:/images
      - ./images/state:/var/lib/docker-qemu
      - ./distros.yaml:/config/distros.yaml:ro
    environment:
      DISTRO: ${VM1_DISTRO:-ubuntu-2404}
      VM_NAME: ${VM1_NAME:-vm1}
      VM_ARCH: ${VM1_ARCH:-x86_64}
      VM_CPU_MODEL: ${VM1_CPU_MODEL:-host}
      VM_CPUS: ${VM1_CPUS:-2}
      VM_MEMORY: ${VM1_MEMORY:-4096}
      VM_DISK_SIZE: ${VM1_DISK_SIZE:-20G}
      VM_DISPLAY: ${VM1_DISPLAY:-none}
      VM_VNC_PORT: ${VM1_VNC_PORT:-5900}
      VM_NOVNC_PORT: ${VM1_NOVNC_PORT:-6080}
      VM_BASE_IMAGE: ${VM1_BASE_IMAGE:-}
      VM_BLANK_DISK: ${VM1_BLANK_DISK:-0}
      VM_BOOT_ISO: ${VM1_BOOT_ISO:-}
      VM_BOOT_ORDER: ${VM1_BOOT_ORDER:-hd}
      VM_CLOUD_INIT: ${VM1_CLOUD_INIT:-1}
      VM_PASSWORD: ${VM1_PASSWORD:-password}
      VM_SSH_PORT: ${VM1_SSH_PORT:-2222}
      VM_SSH_PUBKEY: ${VM1_SSH_PUBKEY:-}
      VM_PERSIST: ${VM1_PERSIST:-1}
      EXTRA_ARGS: ${VM1_EXTRA_ARGS:-}
      REDFISH_USERNAME: ${VM1_REDFISH_USERNAME:-admin}
      REDFISH_PASSWORD: ${VM1_REDFISH_PASSWORD:-password}
      REDFISH_PORT: ${VM1_REDFISH_PORT:-8443}
    ports:
      - "${VM1_SSH_PORT:-2222}:${VM1_SSH_PORT:-2222}"
      - "${VM1_REDFISH_PORT:-8443}:${VM1_REDFISH_PORT:-8443}"
      - "${VM1_VNC_PORT:-5900}:${VM1_VNC_PORT:-5900}"
      - "${VM1_NOVNC_PORT:-6080}:${VM1_NOVNC_PORT:-6080}"
    hostname: ${VM1_NAME:-vm1}
    stdin_open: true
    tty: true
    restart: unless-stopped

  # Duplicate this block (vm2, vm3, ...) for additional VMs.
