name: docker-qemu-ipxe-netbootxyz

services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: ipxe-netbootxyz
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      NGINX_PORT: "8080"
      WEB_APP_PORT: "3000"
      TFTPD_OPTS: >-
        --interface=ipxe-lab-br
        --listen-address=192.0.2.1
        --bind-interfaces
        --dhcp-range=192.0.2.50,192.0.2.100,12h
        --dhcp-option=3,192.0.2.1
        --dhcp-option=6,1.1.1.1
        --dhcp-boot=netboot.xyz.kpxe,,192.0.2.1

  ipxe-client:
    image: ghcr.io/munenick/docker-vm-runner:latest
    container_name: ipxe-client
    hostname: ipxe-client
    restart: unless-stopped
    network_mode: host
    depends_on:
      - netbootxyz
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/kvm:/dev/kvm
      - /dev/net/tun:/dev/net/tun
      - /dev/vhost-net:/dev/vhost-net
    environment:
      GUEST_NAME: ipxe-client
      BOOT_MODE: legacy
      BOOT_ORDER: network,hd
      BLANK_DISK: "1"
      CLOUD_INIT: "0"
      GRAPHICS: novnc
      NOVNC_PORT: "6081"
      VNC_PORT: "5901"
      NETWORK_MODE: bridge
      NETWORK_BRIDGE: ipxe-lab-br
      NETWORK_MODEL: virtio
      NETWORK_BOOT: "1"
      IPXE_ENABLE: "1"
      REQUIRE_KVM: "0"
    volumes:
      - ipxe-client-data:/data

volumes:
  ipxe-client-data:
